"use client";
import { useState } from "react";
import { parseUnits } from "viem";
import { useAccount, useReadContract, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { ARC_USDC, arcTestnet, proofPayAddress } from "@/lib/chain";
import { erc20Abi } from "@/lib/proofpay";
import { buildProofPayWrite, buildUsdcApproval } from "@/lib/transaction-config";

export function CreateBounty(){
  const {address,chainId}=useAccount(); const [error,setError]=useState("");
  const [form,setForm]=useState({title:"",description:"",amount:"",deadline:""});
  const amount=(()=>{try{return parseUnits(form.amount||"0",6)}catch{return 0n}})();
  const {data:allowance,refetch}=useReadContract({address:ARC_USDC,abi:erc20Abi,functionName:"allowance",args:address&&proofPayAddress?[address,proofPayAddress]:undefined,query:{enabled:!!address&&!!proofPayAddress}});
  const approve=useWriteContract(); const create=useWriteContract();
  const receipt=useWaitForTransactionReceipt({hash:create.data});
  const valid=!!address&&chainId===arcTestnet.id&&form.title.trim().length>0&&form.title.length<=120&&form.description.length<=1500&&amount>0n&&!!form.deadline&&new Date(form.deadline).getTime()>Date.now()+600000;
  async function submit(e:React.FormEvent){e.preventDefault();setError("");if(!valid){setError("Check the required fields and choose a deadline at least 10 minutes away.");return}if(!proofPayAddress){setError("ProofPay has not been deployed to the active network yet.");return}try{if((allowance||0n)<amount){await approve.writeContractAsync(buildUsdcApproval(ARC_USDC,proofPayAddress,amount));await refetch();return}await create.writeContractAsync(buildProofPayWrite(proofPayAddress,{functionName:"createTask",args:[form.title.trim(),form.description,amount,BigInt(Math.floor(new Date(form.deadline).getTime()/1000))]}));}catch(err){setError(err instanceof Error?err.message:"Transaction was not completed.")}}
  return <form onSubmit={submit} className="max-w-2xl space-y-5 rounded-lg border border-stone-300 bg-white p-5"><div><label htmlFor="title" className="block text-sm font-medium">Title *</label><input id="title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} maxLength={120} required className="mt-1 w-full rounded-md border border-stone-400 p-3" placeholder="Fix a mobile CSS bug"/><p className="mt-1 text-xs text-stone-600">{form.title.length}/120</p></div><div><label htmlFor="description" className="block text-sm font-medium">Description</label><textarea id="description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} maxLength={1500} rows={6} className="mt-1 w-full rounded-md border border-stone-400 p-3" placeholder="Describe the expected outcome."/><p className="mt-1 text-xs text-stone-600">{form.description.length}/1500</p></div><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="amount" className="block text-sm font-medium">Bounty amount (USDC) *</label><input id="amount" type="text" inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="mt-1 w-full rounded-md border border-stone-400 p-3" placeholder="5.00"/></div><div><label htmlFor="deadline" className="block text-sm font-medium">Submission deadline *</label><input id="deadline" type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className="mt-1 w-full rounded-md border border-stone-400 p-3"/></div></div>{error&&<p role="alert" className="rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}{receipt.isSuccess&&<p className="rounded-md bg-emerald-50 p-3 text-sm text-emerald-800">Bounty created. It will appear after the next read.</p>}<button disabled={!valid||approve.isPending||create.isPending} aria-busy={approve.isPending||create.isPending} className="min-h-11 rounded-md bg-stone-900 px-4 text-sm font-medium text-white disabled:opacity-50">{(allowance||0n)<amount?"Approve exact USDC amount":"Create bounty"}</button>{!address&&<p className="text-sm text-stone-600">Connect a wallet to create a bounty.</p>}{chainId&&chainId!==arcTestnet.id&&<p className="text-sm text-red-700">Switch to the active Arc network before continuing.</p>}</form>
}
