export const Status: Record<string, number> = { OPEN:0, CLAIMED:1, SUBMITTED:2, COMPLETED:3, CANCELLED:4, REFUNDED:5, REJECTED:6 };
export type TaskStatus = (typeof Status)[keyof typeof Status];
export type Task = { id:bigint; creator:`0x${string}`; worker:`0x${string}`; amount:bigint; deadline:bigint; createdAt:bigint; claimedAt:bigint; submittedAt:bigint; status:TaskStatus; title:string; description:string; proofURI:string };
export const statusLabel=(status:TaskStatus)=>["Open","Claimed","Submitted","Completed","Cancelled","Refunded","Rejected"][status] ?? "Unknown";
export const statusTone=(status:TaskStatus)=> status===Status.COMPLETED ? "bg-emerald-100 text-emerald-800" : status===Status.OPEN ? "bg-sky-100 text-sky-800" : status===Status.SUBMITTED ? "bg-amber-100 text-amber-800" : "bg-stone-200 text-stone-700";
export const isZero=(address:string)=>/^0x0{40}$/i.test(address);
export const proofPayAbi = [{type:"function",name:"taskCount",stateMutability:"view",inputs:[],outputs:[{type:"uint256"}]},{type:"function",name:"getTask",stateMutability:"view",inputs:[{name:"taskId",type:"uint256"}],outputs:[{type:"tuple",components:[{name:"id",type:"uint256"},{name:"creator",type:"address"},{name:"worker",type:"address"},{name:"amount",type:"uint256"},{name:"deadline",type:"uint64"},{name:"createdAt",type:"uint64"},{name:"claimedAt",type:"uint64"},{name:"submittedAt",type:"uint64"},{name:"status",type:"uint8"},{name:"title",type:"string"},{name:"description",type:"string"},{name:"proofURI",type:"string"}]}]},{type:"function",name:"createTask",stateMutability:"nonpayable",inputs:[{name:"title",type:"string"},{name:"description",type:"string"},{name:"amount",type:"uint256"},{name:"deadline",type:"uint64"}],outputs:[{type:"uint256"}]},{type:"function",name:"claimTask",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"}],outputs:[]},{type:"function",name:"releaseClaim",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"}],outputs:[]},{type:"function",name:"submitProof",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"},{name:"proofURI",type:"string"}],outputs:[]},{type:"function",name:"approveAndPay",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"}],outputs:[]},{type:"function",name:"rejectAndRefund",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"},{name:"reason",type:"string"}],outputs:[]},{type:"function",name:"cancelTask",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"}],outputs:[]},{type:"function",name:"refundExpiredTask",stateMutability:"nonpayable",inputs:[{name:"taskId",type:"uint256"}],outputs:[]}] as const;
export const proofPayUsdcAbi = [{type:"function",name:"usdc",stateMutability:"view",inputs:[],outputs:[{type:"address"}]}] as const;
export const erc20Abi=[{type:"function",name:"allowance",stateMutability:"view",inputs:[{type:"address",name:"owner"},{type:"address",name:"spender"}],outputs:[{type:"uint256"}]},{type:"function",name:"approve",stateMutability:"nonpayable",inputs:[{type:"address",name:"spender"},{type:"uint256",name:"value"}],outputs:[{type:"bool"}]}] as const;
